version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - run:
          name: Check current version of node
          command: node -v
      - restore_cache:
          keys:
            - node_modules_cache_{{ checksum "package-lock.json" }}
      - run:
          name: Install project dependencies
          command: |
            if [ ! -d "node_modules" ]; then
            npm ci -f
            fi
      - save_cache:
          key: node_modules_cache_{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: npm run coverage
      - store_artifacts:
          path: coverage
      - run:
          name: install sonar scanner
          command: |
            cd /tmp
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip || sudo apt install unzip -y
            unzip sonar-scanner-cli-4.6.2.2472-linux.zip
            cd -
      - run:
          name: Run SonarScanner
          command: /tmp/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner